DATASET_ROOT="~/hudecek/data/camrest/CamRest676.json"
DATA_ROOT="${PROJECT_ROOT}/data"
DOMAIN="camrest"
DATASET_PICKLED="${DATA_ROOT}/camrest_dialogues.pkl"
SEMAFOR_RESULT="${DATA_ROOT}/parsed-camrest-semafor.jsonl"
SESAME_RESULT="${DATA_ROOT}/predicted-camrest-sesame.conll"
