DATASET_ROOT="/home/hudecek/hudecek/data/MultiWOZ_2.1/data.json"
DATA_ROOT="${PROJECT_ROOT}/data"
DOMAIN="woz-hotel"
DATASET_PICKLED="${DATA_ROOT}/woz-hotel_dialogues.pkl"
SEMAFOR_RESULT="${DATA_ROOT}/parsed-woz-hotel-semafor.jsonl"
SESAME_RESULT="${DATA_ROOT}/predicted-woz-hotel-sesame.conll"
